In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
x = np.arange(9)
x = x.reshape(3, 3)

In [5]:
x[1, 1] = 0
x[2, 2] = 0
x

array([[0, 1, 2],
       [3, 0, 5],
       [6, 7, 0]])

In [13]:
indices = np.nonzero(x)
indices = zip(indices[0], indices[1])
indices

[(0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1)]

6

In [31]:
y = np.array([[0, 1], [1, 0]])

In [32]:
test = np.isin(y, [0, 1])

In [33]:
np.all(test)

True

In [52]:
arr = np.array([[2, 3], [1, 0]])
arr
arr.transpose()
(arr.transpose() == arr).all()
(np.diagonal(arr) == 0).all()

False

In [53]:
iu1 = np.triu_indices(arr.shape[0])
arr[iu1]

array([2, 3, 0])

In [54]:
arr

array([[2, 3],
       [1, 0]])

In [55]:
np.sum(arr)

6

In [59]:
test = []
test.insert(2, 3)
test.insert(0, 1)
test

[1, 3]

In [71]:
t = x[:, [0, 1]]
t

array([[0, 1],
       [3, 4],
       [6, 7]])

In [72]:
t = t[[0, 1], :]
t

array([[0, 1],
       [3, 4]])

In [28]:
asdf = [0, 0, 0, 0, 0, 0, 0]


In [31]:
if 1 in asdf:
    print "hello"

In [33]:
test = np.array(asdf)
test.size

7

In [39]:
asdf = np.array([1, 2, 2, 2, 1, 1, 2])
indices = np.where(asdf == asdf.max())
indices

(array([1, 2, 3, 6], dtype=int64),)