In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
x = np.arange(9)
x = x.reshape(3, 3)

In [4]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
y = np.array([[0, 1], [1, 0]])

In [6]:
test = np.isin(y, [0, 1])

AttributeError: 'module' object has no attribute 'isin'

In [ ]:
np.all(test)

In [ ]:
arr = np.array([[2, 3], [1, 0]])
arr
arr.transpose()
(arr.transpose() == arr).all()
(np.diagonal(arr) == 0).all()

In [ ]:
iu1 = np.triu_indices(arr.shape[0])
arr[iu1]

In [ ]:
arr

In [ ]:
np.sum(arr)

In [ ]:
test = []
test.insert(2, 3)
test.insert(0, 1)
test

In [7]:
t = x[:, [0, 1]]
t

array([[0, 1],
       [3, 4],
       [6, 7]])

In [8]:
t = t[[0, 1], :]
t

array([[0, 1],
       [3, 4]])

In [11]:
x[x != 0] = 1
x

array([[0, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

1