In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
x = np.arange(9)
x = x.reshape(3, 3)

In [3]:
x[1, 1] = 0
x[2, 2] = 0
x

array([[0, 1, 2],
       [3, 0, 5],
       [6, 7, 0]])

In [4]:
indices = np.nonzero(x)
indices = zip(indices[0], indices[1])
indices

[(0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1)]

In [5]:
y = np.array([[0, 1], [1, 0]])

In [6]:
test = np.isin(y, [0, 1])

AttributeError: 'module' object has no attribute 'isin'

In [ ]:
np.all(test)

In [ ]:
arr = np.array([[2, 3], [1, 0]])
arr
arr.transpose()
(arr.transpose() == arr).all()
(np.diagonal(arr) == 0).all()

In [7]:
iu1 = np.triu_indices(arr.shape[0])
arr[iu1]

NameError: name 'arr' is not defined

In [8]:
arr

NameError: name 'arr' is not defined

In [9]:
np.sum(arr)

NameError: name 'arr' is not defined

In [10]:
test = []
test.insert(2, 3)
test.insert(0, 1)
test

[1, 3]

In [11]:
t = x[:, [0, 1]]
t

array([[0, 1],
       [3, 0],
       [6, 7]])

In [12]:
t = t[[0, 1], :]
t

array([[0, 1],
       [3, 0]])

In [13]:
asdf = [0, 0, 0, 0, 0, 0, 0]


In [14]:
if 1 in asdf:
    print "hello"

In [15]:
test = np.array(asdf)
test.size

7

In [16]:
asdf = np.array([1, 2, 2, 2, 1, 1, 2])
indices = np.where(asdf == asdf.max())
indices

(array([1, 2, 3, 6], dtype=int64),)

In [23]:
test = [1, 2, 3, 4, 5, 3, 7, 8, 9, 10]
thresh = 7

In [24]:
[num for num in test if num > thresh]

[8, 9, 10]

In [25]:
sum(n_r > thresh for n_r in test)

3