In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
x = np.arange(9)
x = x.reshape(3, 3)

In [3]:
x[1, 1] = 0
x[2, 2] = 0
x

array([[0, 1, 2],
       [3, 0, 5],
       [6, 7, 0]])

In [4]:
indices = np.nonzero(x)
indices = zip(indices[0], indices[1])
indices

In [5]:
y = np.array([[0, 1], [1, 0]])

In [6]:
test = np.isin(y, [0, 1])

In [7]:
np.all(test)

True

In [8]:
arr = np.array([[2, 3], [1, 0]])
arr
arr.transpose()
(arr.transpose() == arr).all()
(np.diagonal(arr) == 0).all()

False

In [9]:
iu1 = np.triu_indices(arr.shape[0])
arr[iu1]

array([2, 3, 0])

In [10]:
arr

array([[2, 3],
       [1, 0]])

In [32]:
x

array([[0, 1, 2],
       [3, 0, 5],
       [6, 7, 0]])

In [58]:
lst = [0, 1]
E = np.nonzero(x[lst[0]])
E[0].size

2

In [52]:
test = list(zip(E[0], E[1]))
test

IndexError: tuple index out of range

In [51]:
x[test[1]]

2

In [12]:
test = []
test.insert(2, 3)
test.insert(0, 1)
test

[1, 3]

In [13]:
t = x[:, [0, 1]]
t

array([[0, 1],
       [3, 0],
       [6, 7]])

In [14]:
t = t[[0, 1], :]
t

array([[0, 1],
       [3, 0]])

In [15]:
asdf = [0, 0, 0, 0, 0, 0, 0]


In [22]:
if 1 in asdf:
    print("hello")

hello


In [17]:
test = np.array(asdf)
test.size

7

In [18]:
asdf = np.array([1, 2, 2, 2, 1, 1, 2])
indices = np.where(asdf == asdf.max())
indices

(array([1, 2, 3, 6], dtype=int64),)

In [19]:
test = [1, 2, 3, 4, 5, 3, 7, 8, 9, 10]
thresh = 7

In [20]:
[num for num in test if num > thresh]

[8, 9, 10]

In [21]:
sum(n_r > thresh for n_r in test)

3